# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
from . import base


# @formatter:off
class AdditionalEmail(base.EntityBase):
    def __init__(
        self,
        id_: int,
        label: str,
        public: bool,
        contactable_id: int,
        contactable_type: str,
        email: str,
    ):
        super().__init__(id_)

        self._label = label
        self._public = public
        self._contactable_id = contactable_id
        self._contactable_type = contactable_type
        self._email = email

    @property
    def label(self) -> str:
        return self._label

    @property
    def public(self) -> bool:
        return self._public

    @property
    def contactable_id(self) -> int:
        return self._contactable_id

    @property
    def contactable_type(self) -> str:
        return self._contactable_type

    @property
    def email(self) -> str:
        return self._email

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["additional_email"]


# @formatter:on
