# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
from . import base


# @formatter:off
class AdditionalAddress(base.EntityBase):
    def __init__(
        self,
        id_: int,
        label: str,
        public: bool,
        contactable_id: int,
        contactable_type: str,
        address_care_of: str,
        street: str,
        housenumber: str,
        postbox: str,
        zip_code: str,
        town: str,
        country: str,
    ):
        super().__init__(id_)

        self._label = label
        self._public = public
        self._contactable_id = contactable_id
        self._contactable_type = contactable_type
        self._address_care_of = address_care_of
        self._street = street
        self._housenumber = housenumber
        self._postbox = postbox
        self._zip_code = zip_code
        self._town = town
        self._country = country

    @property
    def label(self) -> str:
        return self._label

    @property
    def public(self) -> bool:
        return self._public

    @property
    def contactable_id(self) -> int:
        return self._contactable_id

    @property
    def contactable_type(self) -> str:
        return self._contactable_type

    @property
    def address_care_of(self) -> str:
        return self._address_care_of

    @property
    def street(self) -> str:
        return self._street

    @property
    def housenumber(self) -> str:
        return self._housenumber

    @property
    def postbox(self) -> str:
        return self._postbox

    @property
    def zip_code(self) -> str:
        return self._zip_code

    @property
    def town(self) -> str:
        return self._town

    @property
    def country(self) -> str:
        return self._country

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["additional_address"]


# @formatter:on
