# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
import jubladb_api.entities.base


# @formatter:off
class Date(jubladb_api.entities.base.EntityBase):
    def __init__(self,
                 id_: int,
                 
                 event_id: int, 
                 label: str, 
                 location: str, 
                 start_at: str, 
                 finish_at: str, 
                 ):
        super().__init__(id_)
        
        self._event_id = event_id 
        self._label = label 
        self._location = location 
        self._start_at = start_at 
        self._finish_at = finish_at 

    
    @property
    def event_id(self) -> int:
        return self._event_id
    
    @property
    def label(self) -> str:
        return self._label
    
    @property
    def location(self) -> str:
        return self._location
    
    @property
    def start_at(self) -> str:
        return self._start_at
    
    @property
    def finish_at(self) -> str:
        return self._finish_at
    

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["date"]

# @formatter:on