# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
import jubladb_api.entities.base


# @formatter:off
class Event(jubladb_api.entities.base.EntityBase):
    def __init__(self,
                 id_: int,
                 
                 group_ids: int, 
                 type: str, 
                 kind_id: int, 
                 name: str, 
                 description: str, 
                 application_conditions: str, 
                 motto: str, 
                 cost: str, 
                 location: str, 
                 application_opening_at: str, 
                 application_closing_at: str, 
                 application_contact_id: int, 
                 external_application_link: str, 
                 maximum_participants: int, 
                 created_at: str, 
                 updated_at: str, 
                 ):
        super().__init__(id_)
        
        self._group_ids = group_ids 
        self._type = type 
        self._kind_id = kind_id 
        self._name = name 
        self._description = description 
        self._application_conditions = application_conditions 
        self._motto = motto 
        self._cost = cost 
        self._location = location 
        self._application_opening_at = application_opening_at 
        self._application_closing_at = application_closing_at 
        self._application_contact_id = application_contact_id 
        self._external_application_link = external_application_link 
        self._maximum_participants = maximum_participants 
        self._created_at = created_at 
        self._updated_at = updated_at 

    
    @property
    def group_ids(self) -> int:
        return self._group_ids
    
    @property
    def type(self) -> str:
        return self._type
    
    @property
    def kind_id(self) -> int:
        return self._kind_id
    
    @property
    def name(self) -> str:
        return self._name
    
    @property
    def description(self) -> str:
        return self._description
    
    @property
    def application_conditions(self) -> str:
        return self._application_conditions
    
    @property
    def motto(self) -> str:
        return self._motto
    
    @property
    def cost(self) -> str:
        return self._cost
    
    @property
    def location(self) -> str:
        return self._location
    
    @property
    def application_opening_at(self) -> str:
        return self._application_opening_at
    
    @property
    def application_closing_at(self) -> str:
        return self._application_closing_at
    
    @property
    def application_contact_id(self) -> int:
        return self._application_contact_id
    
    @property
    def external_application_link(self) -> str:
        return self._external_application_link
    
    @property
    def maximum_participants(self) -> int:
        return self._maximum_participants
    
    @property
    def created_at(self) -> str:
        return self._created_at
    
    @property
    def updated_at(self) -> str:
        return self._updated_at
    

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["event"]

# @formatter:on