# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
from . import base


# @formatter:off
class EventKindCategory(base.EntityBase):
    def __init__(
        self,
        id_: int,
        label: str,
        order: int,
    ):
        super().__init__(id_)

        self._label = label
        self._order = order

    @property
    def label(self) -> str:
        return self._label

    @property
    def order(self) -> int:
        return self._order

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["event_kind_category"]


# @formatter:on
