# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
import jubladb_api.entities.base

import datetime


# @formatter:off
class Group(jubladb_api.entities.base.EntityBase):
    def __init__(self,
                 id_: int,
                 
                 name: str, 
                 short_name: str, 
                 display_name: str, 
                 description: str, 
                 layer: bool, 
                 parent_id: int, 
                 layer_group_id: int, 
                 type: str, 
                 email: str, 
                 address: str, 
                 zip_code: int, 
                 town: str, 
                 country: str, 
                 require_person_add_requests: bool, 
                 self_registration_url: str, 
                 archived_at: datetime.datetime, 
                 created_at: datetime.datetime, 
                 updated_at: datetime.datetime, 
                 deleted_at: datetime.datetime, 
                 logo: str, 
                 ):
        super().__init__(id_)
        
        self._name = name 
        self._short_name = short_name 
        self._display_name = display_name 
        self._description = description 
        self._layer = layer 
        self._parent_id = parent_id 
        self._layer_group_id = layer_group_id 
        self._type = type 
        self._email = email 
        self._address = address 
        self._zip_code = zip_code 
        self._town = town 
        self._country = country 
        self._require_person_add_requests = require_person_add_requests 
        self._self_registration_url = self_registration_url 
        self._archived_at = archived_at 
        self._created_at = created_at 
        self._updated_at = updated_at 
        self._deleted_at = deleted_at 
        self._logo = logo 

    
    @property
    def name(self) -> str:
        return self._name
    
    @property
    def short_name(self) -> str:
        return self._short_name
    
    @property
    def display_name(self) -> str:
        return self._display_name
    
    @property
    def description(self) -> str:
        return self._description
    
    @property
    def layer(self) -> bool:
        return self._layer
    
    @property
    def parent_id(self) -> int:
        return self._parent_id
    
    @property
    def layer_group_id(self) -> int:
        return self._layer_group_id
    
    @property
    def type(self) -> str:
        return self._type
    
    @property
    def email(self) -> str:
        return self._email
    
    @property
    def address(self) -> str:
        return self._address
    
    @property
    def zip_code(self) -> int:
        return self._zip_code
    
    @property
    def town(self) -> str:
        return self._town
    
    @property
    def country(self) -> str:
        return self._country
    
    @property
    def require_person_add_requests(self) -> bool:
        return self._require_person_add_requests
    
    @property
    def self_registration_url(self) -> str:
        return self._self_registration_url
    
    @property
    def archived_at(self) -> datetime.datetime:
        return self._archived_at
    
    @property
    def created_at(self) -> datetime.datetime:
        return self._created_at
    
    @property
    def updated_at(self) -> datetime.datetime:
        return self._updated_at
    
    @property
    def deleted_at(self) -> datetime.datetime:
        return self._deleted_at
    
    @property
    def logo(self) -> str:
        return self._logo
    

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["group"]

# @formatter:on