# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
from . import base


# @formatter:off
class InvoiceItem(base.EntityBase):
    def __init__(
        self,
        id_: int,
        invoice_id: int,
        name: str,
        description: str,
        cost: int,
        count: int,
        cost_center: str,
        account: str,
    ):
        super().__init__(id_)

        self._invoice_id = invoice_id
        self._name = name
        self._description = description
        self._cost = cost
        self._count = count
        self._cost_center = cost_center
        self._account = account

    @property
    def invoice_id(self) -> int:
        return self._invoice_id

    @property
    def name(self) -> str:
        return self._name

    @property
    def description(self) -> str:
        return self._description

    @property
    def cost(self) -> int:
        return self._cost

    @property
    def count(self) -> int:
        return self._count

    @property
    def cost_center(self) -> str:
        return self._cost_center

    @property
    def account(self) -> str:
        return self._account

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["invoice_item"]


# @formatter:on
