# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
from . import base


# @formatter:off
class PersonName(base.EntityBase):
    def __init__(
        self,
        id_: int,
        first_name: str,
        last_name: str,
    ):
        super().__init__(id_)

        self._first_name = first_name
        self._last_name = last_name

    @property
    def first_name(self) -> str:
        return self._first_name

    @property
    def last_name(self) -> str:
        return self._last_name

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["person_name"]


# @formatter:on
