# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
from . import base

import datetime


# @formatter:off
class Role(base.EntityBase):
    def __init__(
        self,
        id_: int,
        created_at: datetime.datetime,
        updated_at: datetime.datetime,
        start_on: datetime.date,
        end_on: datetime.date,
        name: str,
        person_id: int,
        group_id: int,
        type: str,
        label: str,
    ):
        super().__init__(id_)

        self._created_at = created_at
        self._updated_at = updated_at
        self._start_on = start_on
        self._end_on = end_on
        self._name = name
        self._person_id = person_id
        self._group_id = group_id
        self._type = type
        self._label = label

    @property
    def created_at(self) -> datetime.datetime:
        return self._created_at

    @property
    def updated_at(self) -> datetime.datetime:
        return self._updated_at

    @property
    def start_on(self) -> datetime.date:
        return self._start_on

    @property
    def end_on(self) -> datetime.date:
        return self._end_on

    @property
    def name(self) -> str:
        return self._name

    @property
    def person_id(self) -> int:
        return self._person_id

    @property
    def group_id(self) -> int:
        return self._group_id

    @property
    def type(self) -> str:
        return self._type

    @property
    def label(self) -> str:
        return self._label

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["role"]


# @formatter:on
