# This file is auto-generated by generate_entities.py
import jubladb_api.metamodel
import jubladb_api.entities.base


# @formatter:off
class SocialAccount(jubladb_api.entities.base.EntityBase):
    def __init__(self,
                 id_: int,
                 
                 label: str, 
                 public: bool, 
                 contactable_id: int, 
                 contactable_type: str, 
                 name: str, 
                 ):
        super().__init__(id_)
        
        self._label = label 
        self._public = public 
        self._contactable_id = contactable_id 
        self._contactable_type = contactable_type 
        self._name = name 

    
    @property
    def label(self) -> str:
        return self._label
    
    @property
    def public(self) -> bool:
        return self._public
    
    @property
    def contactable_id(self) -> int:
        return self._contactable_id
    
    @property
    def contactable_type(self) -> str:
        return self._contactable_type
    
    @property
    def name(self) -> str:
        return self._name
    

    @property
    def meta(self) -> jubladb_api.metamodel.Entity:
        return jubladb_api.metamodel.ENTITIES["social_account"]

# @formatter:on